# Generated by Django 6.0 on 2025-12-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timereport',
            name='job_group',
            field=models.CharField(default=''),
        ),
    ]
