# Generated by Django 6.0 on 2025-12-27 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_timereport_job_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='timereport',
            name='report_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timesheets.report', to_field='report_id'),
            preserve_default=False,
        ),
    ]
