# Generated by Django 6.0 on 2025-12-27 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_report_timereport_report_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timereport',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='timereport',
            old_name='report_id',
            new_name='report',
        ),
    ]
