# Generated by Django 6.0 on 2025-12-27 23:57

import django.db.models.deletion
from django.db import migrations, models


def create_initial_job_groups(apps, schema_editor):
    JobGroup = apps.get_model('timesheets', 'JobGroup')
    JobGroup.objects.create(name='A', hourly_rate=20.0)
    JobGroup.objects.create(name='B', hourly_rate=30.0)


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_rename_employee_id_timereport_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='timereport',
            name='job_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheets.jobgroup', to_field='name'),
        ),
        migrations.RunPython(create_initial_job_groups),
    ]
